export const APP_AUTHORIZATION_TYPES = {
  APP_LOGINIZATION_DATA: 'APP/LOGINIZATION/DATA',
  APP_AUTHORIZATION_DATA: 'APP/AUTHORIZATION/DATA',
  APP_AUTHORIZATION_ERROR_DATA: 'APP/AUTHORIZATION/ERROR/DATA',
};

export const APP_ACTION_TYPES = {
  APP_IS_LOADING: 'APP/IS/LOADING',
  APP_IS_LOADING_REFRESH_LIST: 'APP/IS/LOADING/REFRESH/LIST',
  APP_IS_DISABLE_MODE_ACTIVE: 'APP/IS/DISABLE/MODE/ACTIVE',
  APP_UPDATE_TOTAL_PACKS_COUNT: 'APP/UPDATE/TOTAL/PACKS/COUNT',
  APP_UPDATE_TOTAL_CARDS_COUNT: 'APP/UPDATE/TOTAL/CARDS/COUNT',
  APP_UPLOAD_AVATAR_ERROR_DATA: 'APP/UPLOAD/AVATAR/ERROR/DATA',
};

export const APP_PACKS_TYPES = {
  APP_GET_PACKS: 'APP/GET/PACKS',
  APP_SET_NEXT_PACK: 'APP/SET/NEXT/PACK',
  APP_SET_NEW_PACK: 'APP/SET/NEW/PACK',
  APP_CHANGE_PACK_TITLE: 'APP/CHANGE/PACK/TITLE',
  APP_SET_DELETE_PACK: 'APP/SET/DELETE/PACK',
  APP_SET_SEARCH_PACK_NAME: 'APP/SET/SEARCH/PACK/NAME',
  APP_SET_MAX_COUNT_PAGE: 'APP/SET/MAX/COUNT/PAGE',
};

export const APP_CARDS_TYPES = {
  APP_SET_CARD_PACK_ID: 'APP/SET/CARDS/PACK/ID',
  APP_GET_CARDS: 'APP/GET/CARDS',
  APP_SET_SEARCH_CARD_QUESTION: 'APP/SET/SEARCH/CARD/QUESTION',
  APP_DELETE_CARD: 'APP/DELETE/CARD',
};
