export const TYPES = {
  APP_LOGINIZATION_DATA: 'APP/LOGINIZATION/DATA',
  APP_AUTHORIZATION_DATA: 'APP/AUTHORIZATION/DATA',
  APP_AUTHORIZATION_ERROR_DATA: 'APP/AUTHORIZATION/ERROR/DATA',
};

export const APP_ACTION_TYPES = {
  APP_IS_LOADING: 'APP/IS/LOADING',
};

export const APP_PACKS_TYPES = {
  APP_GET_PACKS: 'APP/GET/PACKS',
  APP_SET_NEXT_PACK: 'APP/SET/NEXT/PACK',
  APP_SET_NEW_PACK: 'APP/SET/NEW/PACK',
  APP_SET_DELETE_PAGE: 'APP/SET/DELETE/PAGE',
  APP_SET_SEARCH_PACK_NAME: 'APP/SET/SEARCH/PACK/NAME',
  APP_SET_MAX_COUNT_PAGE: 'APP/SET/MAX/COUNT/PAGE',
};
