export const Screens = {
  DRAWER_SCREENS: 'DRAWER_SCREENS',
  BOTTOM_TAB_SCREENS: 'BOTTOM_TAB_SCREENS',
  FORM_SCREEN: 'FORM_SCREEN',
  PACKS_SCREEN: 'PACKS_SCREEN',
  CARDS_SCREEN: 'CARDS_SCREEN',
  PROFILE_SCREEN: 'PROFILE_SCREEN',
  PROFILE_CHANGE_SCREEN: 'PROFILE_CHANGE_SCREEN',
};
