export const Screens = {
  BOTTOM_TAB_SCREEN: ' BOTTOM_TAB_SCREEN',
  FORM_SCREEN: 'FORM_SCREEN',
  PACKS_SCREEN: 'PACKS_SCREEN',
  CARDS_SCREEN: 'CARDS_SCREEN',
  PROFILE_SCREEN: 'PROFILE_SCREEN',
  PROFILE_CHANGE_SCREEN: 'PROFILE_CHANGE_SCREEN',
};
